### ISSUE TITLE
Sending parameters to scss file

### ISSUE THREAD

**Issue by angelpcadena** [Taritsyn/BundleTransformer#1]
Hello, is there any way to send parameteres to a scss file and using them as variables?

`@Styles.Render("~/css/base.css?param1=red")`
or
`<link rel="stylesheet" href="assets/css/base.scss?param1=red" type="text/css">`

and in the scss file:
`$myVar= $param1;
body {
    color: $myVar;
    font-size: 16px;
}`

**Comment by Taritsyn** [comment]
Hello, Angel!

> Hello, is there any way to send parameteres to a scss file and using them as variables?

There is no such possibility and its implementation is not planned.

> `@Styles.Render("~/css/base.css?param1=red")`

`Styles.Render` and `Scripts.Render` methods can take only the URLs of bundles. I recommend you to read the [Microsoft ASP.NET Web Optimization Framework's documentation](https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/bundling-and-minification).

But you have the ability to inject a Sass variables by using the custom item transformation.

First, create a custom item transformation:

```csharp
using System.Text;
using System.Web.Optimization;

public sealed class InjectContentItemTransform : IItemTransform
{
	private readonly string _beforeContent;
	private readonly string _afterContent;


	public InjectContentItemTransform(string beforeContent)
		: this(beforeContent, string.Empty)
	{ }

	public InjectContentItemTransform(string beforeContent, string afterContent)
	{
		_beforeContent = beforeContent ?? string.Empty;
		_afterContent = afterContent ?? string.Empty;
	}


	public string Process(string includedVirtualPath, string input)
	{
		if (_beforeContent.Length == 0 && _afterContent.Length == 0)
		{
			return input;
		}

		var contentBuilder = new StringBuilder();
		if (_beforeContent.Length > 0)
		{
			contentBuilder.AppendLine(_beforeContent);
		}
		contentBuilder.AppendLine(input);
		if (_afterContent.Length > 0)
		{
			contentBuilder.AppendLine(_afterContent);
		}

		return contentBuilder.ToString();
	}
}
```

And then register this transformation as follows:

```csharp
using System.Web.Optimization;

using BundleTransformer.Core.Bundles;
using BundleTransformer.Core.Orderers;
using BundleTransformer.Core.Resolvers;

namespace TestSassVariables
{
	public class BundleConfig
	{
		public static void RegisterBundles(BundleCollection bundles)
		{
			var nullOrderer = new NullOrderer();

			// Replace a default bundle resolver in order to the debugging HTTP handler
			// can use transformations of the corresponding bundle
			BundleResolver.Current = new CustomBundleResolver();

			const string beforeScssCodeToInject = @"$myVar: red;";

			var commonStylesBundle = new CustomStyleBundle("~/Bundles/CommonStyles");
			commonStylesBundle.Include("~/assets/css/base.scss",
				new InjectContentItemTransform(beforeScssCodeToInject));
			commonStylesBundle.Orderer = nullOrderer;

			bundles.Add(commonStylesBundle);
		}
	}
}
```

If you are create a multi-tenant web application, then perhaps you may have to write your own implementation of the <code title="System.Web.Optimization.IBundleCache">IBundleCache</code> interface, <code title="System.Web.Hosting.VirtualPathProvider">VirtualPathProvider</code> class and own version of the <code title="BundleTransformer.SassAndScss.HttpHandlers.SassAndScssAssetHandler">SassAndScssAssetHandler</code> class with an overridden `GetCacheKey` method. I recommend  you familiarize with source code of the [SmartStore.NET](https://github.com/smartstoreag/SmartStoreNET) project.

> `<link rel="stylesheet" href="assets/css/base.scss?param1=red" type="text/css">`

If you only need this functionality, then you can abandon the Microsoft ASP.NET Web Optimization Framework and Bundle Transformer. Just write your own HTTP handler, which will directly use the [LibSass Host for .NET](https://github.com/Taritsyn/LibSassHost) library.

**Comment by angelpcadena** [comment]
Thank you very much for the detailed response, I'm going to evaluate the need for the Web Optimization Framework since we're testing .net PushPromise, in fact we were only using the BundleTransform library since it already comes with an HTTP handler for .scss files.

Thanks again!

**Comment by Taritsyn** [comment]
> …, in fact we were only using the BundleTransform library since it already comes with an HTTP handler for .scss files.

Usage of the debugging HTTP handler ([`SassAndScssAssetHandler`](https://github.com/Taritsyn/BundleTransformer/blob/master/src/BundleTransformer.SassAndScss/HttpHandlers/SassAndScssAssetHandler.cs)) on a production server is not a good idea.

**Comment by angelpcadena** [comment]
Could this functionality be achieved with a custom HTTP handler or is the nature the feature?

**Comment by Taritsyn** [comment]
If you want to inject a Sass variables in the Bundle Transformer, then you definitely  need to register the bundles.

If you want to create a custom HTTP handler, that uses the [LibSass Host for .NET](https://github.com/Taritsyn/LibSassHost) library, then you do not need the Bundle Transformer. But in this case, you will have to independently implement the parsing of query string, reading of file from disk, its processing and caching. Also you should understand, that injection of Sass variables is simply adding a piece of code at the beginning of Sass file contents.
