### ISSUE TITLE
Variable interpolation in import statements not overridden by ModifyVariables values when default is present

### ISSUE THREAD

**Issue by athoma13** [Taritsyn/BundleTransformer#10]
Hi,

I have the following in a less file:

`
@button-style: 'flat';
...
import 'less/button-@{button-style}.less';
`
This works fine and imports button-flat.less.

However, when I use the **LessTranslator.ModifyVariables** = "button-style='raised'";

Expected:
import 'less/button-raised.less';
Actual:
import 'less/button-flat.less';

Additional.
When I don't define a 'default' value in the less file, then the value from ModifyVariables is used.
This behaviour only happens for imports - other variables 'default' values are overridden from ModifyVariables properly.

**Comment by Taritsyn** [comment]
Hello!

Most likely, your web application is in debug mode and you did not add the following code to `App_Start/BundleConfig.cs` file:

```csharp
BundleResolver.Current = new CustomBundleResolver();
```

For more detailed information, see the [“Examples of usage” ](https://github.com/Taritsyn/BundleTransformer/wiki/Examples-of-usage) and [“Debugging HTTP handlers”](https://github.com/Taritsyn/BundleTransformer/wiki/Debugging-HTTP-handlers) sections of documentation.

**Comment by athoma13** [comment]
Hi Taritsyn,

No, that isn't the case. I should have made this a little clearer perhaps.
The less file in question is imported from another less file.

i.e.: 

site.less
`import 'less/less-file-containing-interpolated-imports.less'`

less-file-containing-interpolated-imports.less
`
@button-style: 'flat'; 
... 
import 'less/button-@{button-style}.less';
`

...the interpolated import doesn't work in less-file-containing-interpolated-imports.less

**Comment by Taritsyn** [comment]
For this example, you will get a similar result even if you use the original LESS compiler.

To test this, first install the Node.js module:

```
npm install -g less
```

And then run the following commands:

```
cd YOUR-DIRECTORY-WITH-STYLESHEETS
lessc --modify-var="button-style='raised'" site.less
```
