### ISSUE TITLE
Nuget package install does not add BundleTransformer reference to a WebForms web application project

### ISSUE THREAD

**Issue by LewieMac** [Taritsyn/BundleTransformer#11]
When I install the Nuget package, I still have to add a reference to the web application project.

Is the issue to do with the fact that the project is a WebForms web applications?

**Comment by Taritsyn** [comment]
Hello!

I could not reproduce this error. You could make a demonstration project, which reproduce this error.

**Comment by LewieMac** [comment]
Hi!

I can't seem to reproduce the issue on anything but the specific project I'm working on which would probably point to the problem specific to my project.

Sorry to waste your time.
