### ISSUE TITLE
Less compiler (lessc) include paths support

### ISSUE THREAD

**Issue by williamwilson** [Taritsyn/BundleTransformer#14]
Is there support for specifying the --include-path ([http://lesscss.org/usage/#command-line-usage-include-paths](url)) command line arg when using the less translator?  Browsing the source it appears there are 10 or so compiler options supported, but I don't see this one explicitly.  Perhaps I'm missing it?

Or perhaps there is another means to supply additional import resolution paths?

**Comment by Taritsyn** [comment]
Hello, William!

Upgrade the Bundle Transformer to [version 1.9.189](https://github.com/Taritsyn/BundleTransformer/releases/tag/v1.9.189). If you do not use the [BundleTransformer.ConfigurationIntelliSense](https://www.nuget.org/packages/BundleTransformer.ConfigurationIntelliSense/) package, then I recommend you to install it.

You can specify a include paths (only virtual paths are supported) in the `Web.config` file as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  …
  <bundleTransformer xmlns="http://tempuri.org/BundleTransformer.Configuration.xsd">
    …
    <less …>
      …
      <includePaths>
        <add path="~/AlternativeContent/less/" />
        <add path="~/AlternativeContent/css/" />
      </includePaths>
      …
    </less>
    …
  </bundleTransformer>
  …
</configuration>
```

**Comment by williamwilson** [comment]
Thanks for the quick turn around.  I'll look into upgrading.
