### ISSUE TITLE
Regex for UglifyJS

### ISSUE THREAD

**Issue by aachir** [Taritsyn/BundleTransformer#15]
Hi

Will it be possible to provide a regex for mangling properties, i.e. to passthrough to mangle_props.regex (I think this is how it should look).

Thanks
Andrey

**Comment by Taritsyn** [comment]
Hello!

Mangling properties is not supported. At the moment, I simply do not have time to develop the BundleTransformer.UglifyJs module, because I have other priorities.

**Comment by aachir** [comment]
Andrey

Many thanks for the prompt reply.

Best wishes
Andrey
