### ISSUE TITLE
Unable to get test .ts files to include

### ISSUE THREAD

**Issue by mrstarware** [Taritsyn/BundleTransformer#17]
Hi, 
I'm trying to bundle .ts files in a hybrid .net / angular application.
Inside of BundleConfig.cs I have 
```
        var tsBundle = new CustomScriptBundle("~/Bundles/TypeScripts");
        tsBundle.IncludeDirectory("~/app/src/app/test/", "*.ts", true);
        tsBundle.Transforms.Add(scriptTransformer);
        tsBundle.Orderer = nullOrderer;
        bundles.Add(tsBundle);
```

However when I include in my page 

    <%: Scripts.Render("~/Bundles/TypeScripts")  %>

I am told that the assets are not scripts?

**Comment by Taritsyn** [comment]
Hello!

Have you installed the [BundleTransformer.TypeScript](https://github.com/Taritsyn/BundleTransformer/wiki/Bundle-Transformer:-TypeScript) package?

**Comment by mrstarware** [comment]
Yes, although I am wondering what the necessary prerequisites are? I'm wondering if my project might be incompatible or require additional configuration in the web.config files?

**Comment by Taritsyn** [comment]
The following line is unnecessary:

```csharp
tsBundle.Transforms.Add(scriptTransformer);
```

I will not explain why, it is better to look at the [documentation](https://github.com/Taritsyn/BundleTransformer/wiki/Examples-of-usage).

```xml
<fileExtensions>
	…
	<add fileExtension=".ts" assetTypeCode="TypeScript" />
	…
</fileExtensions>
```

This setting is added to the `Web.config` file during  installation of the [BundleTransformer.TypeScript](https://www.nuget.org/packages/BundleTransformer.TypeScript) package.

```
Error: Method 'ts.sys.directoryExists' is not implemented
```

Do you use external modules?

**Comment by mrstarware** [comment]
We do import several modules.

**Comment by Taritsyn** [comment]
I will quote the [documentation](https://github.com/Taritsyn/BundleTransformer/wiki/Bundle-Transformer:-TypeScript):

> BundleTransformer.TypeScript does not support external modules (CommonJS, AMD, SystemJS, UMD and ES6 modules).

For your tasks you need a more modern tool: [Grunt](https://gruntjs.com/), [Gulp](https://gulpjs.com/) or [Webpack](https://webpack.js.org/).
