### ISSUE TITLE
LessAssetHandler and Virtual Path Providers

### ISSUE THREAD

**Issue by ZNS** [Taritsyn/BundleTransformer#18]
Hello!

I've made a custom virtual path provider which serves a dynamic less-file. However it doesn't work with the LessAssetHandler. I get a 404.

**Comment by Taritsyn** [comment]
Hello, Ulrik!

Everything should work. Try to solve this problem yourself by using a Visual Studio debugger.

**Comment by ZNS** [comment]
Problem solved! I removed resourceType="File" from the handler in web.config
