### ISSUE TITLE
.Net Core support?

### ISSUE THREAD

**Issue by dehghani-mehdi** [Taritsyn/BundleTransformer#21]
Hi,

Is any plan to support .Net core?

**Comment by Taritsyn** [comment]
Hello, Mehdi!

There are plans, no time.

About [this issue](https://github.com/xoofx/SharpScss/issues/10): [LibSass Host for .NET](https://github.com/Taritsyn/LibSassHost) also supports .NET Core.

**Comment by Taritsyn** [comment]
> I'm wondering which engine do you want to use?

[JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore)

**Comment by dehghani-mehdi** [comment]
Nice, now I have autoprefixer support for my project! thanks bro for the help. I'm done here, feel free to close the issue or keep it open.

**Comment by Taritsyn** [comment]
Hello, Mehdi!

Try to use the [Autoprefixer Host](https://github.com/Taritsyn/AutoprefixerHost) library.

**Comment by dehghani-mehdi** [comment]
Hi Andrey,

Nice library, actually I did same thing for my project using Chakra, but thanks for your attention.
