### ISSUE TITLE
request build source for less-combined.js

### ISSUE THREAD

**Issue by mikejf-pr** [Taritsyn/BundleTransformer#24]
Is the process of creating less-combined.js from less.js automated and is the elements something that can be made available?

**Comment by Taritsyn** [comment]
Hello!

I'm building the `less-combined.js` file manually. I will add support for version 3.8.1 in next week.

**Comment by Taritsyn** [comment]
In [version 1.9.215](https://github.com/Taritsyn/BundleTransformer/releases/tag/v1.9.215) added support of LESS version 3.8.1.
