### ISSUE TITLE
These assets are not style sheets error for virtual path with no dots

### ISSUE THREAD

**Issue by SylviaJ** [Taritsyn/BundleTransformer#3]
Hi,

I have embedded less sheets for which I use an EmbeddedResourceRouteHandler / EmbeddedVirtualFile system to load the embedded resources.
Because it is a virtual path, the path cannot end in .less as otherwise it thinks it is an actual physical file and just tries to load it instead of using the resource route handler.
And because they are embedded resources, I can have no dots in the directory / file names.

Therefore I get the "These assets are not style sheets" error because of this code in your 
FileExtensionMappingCollection class; GetAssetTypeCodeByFilePath method
  ```
  int dotCount = processedAssetPath.Count(c => c == '.');

if (dotCount == 0)
{
	return Constants.AssetTypeCode.Unknown;
}
```

If the if statement was removed everything would work fine - as it would fall to the part 

```
   foreach (string fileExtension in fileExtensions)
  {
        if (processedAssetPath.EndsWith(fileExtension))
	{
			assetFileExtension = fileExtension;
			break;
        }
    }
```

as /less has been added as a valid FileExtension in the config file.

Is there any reason for the  `if(dotCount == 0) `  lines of code? 
Would it be possible to remove it and get a new version of BundleTransformer out??

Thanks

**Comment by Taritsyn** [comment]
Hello, Sylvia!

> Because it is a virtual path, the **path cannot end in .less** as otherwise it thinks it is an actual physical file and just tries to load it instead of using the resource route handler.

This is your main problem.

Architecture of the Bundle Transformer is focused on working with the classic file extensions. I think that you need another tool.
