### ISSUE TITLE
Can I get minified string of processed bundle at .cshtml?

### ISSUE THREAD

**Issue by ericfelipe99** [Taritsyn/BundleTransformer#30]
Hi, 

I need to make some tests of performance.. .so... can i get the minified version of a bundle ? 

for example: 
```
<style>
@GetMinifiedBundle([bundlepath]); 
 </style>
```

**Comment by Taritsyn** [comment]
Hello, Eric!

I recommend you to look at the source code of the [Microsoft ASP.NET Web Optimization Framework](https://archive.codeplex.com/?p=aspnetoptimization).

**Comment by ericfelipe99** [comment]
> Hello, Eric!
> 
> I recommend you to look at the source code of the [Microsoft ASP.NET Web Optimization Framework](https://archive.codeplex.com/?p=aspnetoptimization).

tanks for reply. 

is that another library ? So i can't do it with bundle transformer ?

Thanks again.

**Comment by Taritsyn** [comment]
> is that another library ? So i can't do it with bundle transformer ?

Apparently you did not even read the [`README.md`](https://github.com/Taritsyn/BundleTransformer/blob/master/README.md) file:

> Bundle Transformer - a modular extension for the [System.Web.Optimization](http://aspnetoptimization.codeplex.com/) (also known as the Microsoft ASP.NET Web Optimization Framework). `StyleTransformer` and `ScriptTransformer` classes, included in the core of Bundle Transformer and implement the `IBundleTransform` interface. They are intended to replace the standard classes: `CssMinify` and `JsMinify`.
> …

I also recommend you to read the [“Before you read”](https://github.com/Taritsyn/BundleTransformer/wiki/Before-you-read) section of documentation.

**Comment by ericfelipe99** [comment]
> > is that another library ? So i can't do it with bundle transformer ?
> 
> Apparently you did not even read the [`README.md`](https://github.com/Taritsyn/BundleTransformer/blob/master/README.md) file:
> 
> > Bundle Transformer - a modular extension for the [System.Web.Optimization](http://aspnetoptimization.codeplex.com/) (also known as the Microsoft ASP.NET Web Optimization Framework). `StyleTransformer` and `ScriptTransformer` classes, included in the core of Bundle Transformer and implement the `IBundleTransform` interface. They are intended to replace the standard classes: `CssMinify` and `JsMinify`.
> > …
> 
> I also recommend you to read the [“Before you read”](https://github.com/Taritsyn/BundleTransformer/wiki/Before-you-read) section of documentation.

I think that you guys that work on these libraries may know about that. 
Apparently the link you got to me didn't have anything about my question neither the project isn't open source. 

thanks for your reply

closed topic.

**Comment by Taritsyn** [comment]
> I think that you guys that work on these libraries may know about that.

I wrote the Bundle Transformer back in 2012, and of course I can't remember the whole object model of the Microsoft ASP.NET Web Optimization Framework library, which is not developing from 2014.

> … the project isn't open source.

You're wrong - https://codeplexarchive.blob.core.windows.net/archive/projects/aspnetoptimization/aspnetoptimization.zip.
