### ISSUE TITLE
Proxy settings?

### ISSUE THREAD

**Issue by AnReZa** [Taritsyn/BundleTransformer#34]
How can I set up a proxy authentication with Closure remote access? Our proxy requires user name and password.

**Comment by Taritsyn** [comment]
Hello, André!

Try experimenting with settings in the [`configuration\system.net\defaultProxy`](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings) section of `Web.config` file.
