### ISSUE TITLE
Basic config in wiki docs, fail to skip minified files ending with *.min.js & *.min.css extensions.

### ISSUE THREAD

**Issue by JimiGR1** [Taritsyn/BundleTransformer#37]
Im using the improved example (end of the page) found here:
https://github.com/Taritsyn/BundleTransformer/wiki/Examples-of-usage

Using MicrosoftAjaxJsMinifier as default jsMinifier in web.config. and CustomScriptBundle that contains some pre-minifed files with *.min.js extensions.

By reading the docs I ended up in the conclusion that above mentioned files should be skipped from ninification process by default, based on .min.js extension, but that's not the case.

I get erros from MicrosoftAjaxJsMinifier inside those .min files, meaning that they aren't actually skipped from minification.

Is it a misconfiguration by my part? Or my conclusion is wrong in the first place?

**Comment by Taritsyn** [comment]
Hello!

Try making a demo project that reproduces this error and send me a link to it.

**Comment by JimiGR1** [comment]
Thank you for the fast response.
Here is the demo:

https://www.dropbox.com/s/ls8eo1b8aschf6e/BundleTransformerDemo.zip?dl=0

**Comment by Taritsyn** [comment]
Rename a `ol-min.js` file to the `ol.min.js` file.

**Comment by JimiGR1** [comment]
That was it! It is matching *.min.js.
Thank you for your excellent support.

This is one of my favorite packages. Keep it up!
