### ISSUE TITLE
Feature Request: .NET Standard Support

### ISSUE THREAD

**Issue by samtrion** [Taritsyn/BundleTransformer#40]
Based on current developments, support for at least .NET Standard 2.0 would be very beneficial.

**Comment by Taritsyn** [comment]
Hello, Martin!

The base library ([System.Web.Optimization](http://aspnetoptimization.codeplex.com/)) does not support .NET Standard. A complete rewrite of the Bundle Transformer library will require a large amount of resources, which I do not currently have.

**Comment by Taritsyn** [comment]
I recommend that you look at the Mads Kristensen's project - [WebOptimizer](https://github.com/ligershark/WebOptimizer).

**Comment by samtrion** [comment]
Thanks for your reponse.
