### ISSUE TITLE
Virtual Directory Error When Using CustomStyleBundle on Azure Website

### ISSUE THREAD

**Issue by koimad** [Taritsyn/BundleTransformer#45]
Hi I get the following error when using CustomStyleBundle on an azure website.

System.ArgumentException: Directory does not exist.
Parameter name: directoryVirtualPath
  at System.Web.Optimization.Bundle.IncludeDirectory(String directoryVirtualPath, String searchPattern, Boolean searchSubdirectories)
  at School.Components.BundleConfig.RegisterBundles(BundleCollection bundles) in C:\Users\koima\source\repos\School-8\School-8\Components\BundleComponent.cs:line 53

StyleBundle works fine for normal css files.

Everything works fine on a local IIS server.

**Comment by Taritsyn** [comment]
Hello!

> … on an azure website.

Unfortunately, I don't use the Azure.

> at System.Web.Optimization.Bundle.IncludeDirectory(String directoryVirtualPath, String searchPattern, Boolean searchSubdirectories)
> at School.Components.BundleConfig.RegisterBundles(BundleCollection bundles) in C:\Users\koima\source\repos\School-8\School-8\Components\BundleComponent.cs:line 53

Is it really a full stack trace?

> StyleBundle works fine for normal css files.

Do you use a BundleTransformer.Less and BundleTransformer.SassAndScss modules?

> Everything works fine on a local IIS server.

Are you sure that the settings of virtual directories on the local IIS server and the Azure are same?

**Comment by koimad** [comment]
Hi it was my mistake, one of the directories did not deploy correctly. Once I manually deployed the files all worked fine.
