### ISSUE TITLE
LibSass Deprecated by Sass

### ISSUE THREAD

**Issue by filefontaine** [Taritsyn/BundleTransformer#47]
Hello,

i have see that **LibSass** is know Deprecated and **Sass** recommanded to use **DartSass** instead.
https://sass-lang.com/blog/libsass-is-deprecated

(and Bootstrap 5 recommand **DartSass** )

I wanted to know if you have any plans to add compatibility for dartSass on _BundleTransformer.SassAndScss_ ?

**Comment by Taritsyn** [comment]
Hello, Antoine!

I've known about this for a long time, so I started working on the [Sass Host](https://github.com/Taritsyn/SassHost) project. While work on this project is stopped, but I will return to it as soon as I have free time.

**Comment by HRasch** [comment]
Love to read this :-)

**Comment by HRasch** [comment]
Now Bootstrap 5.2 is released and uses some calc-functions that can't be compiled with LibSass anymore :-( Is this issue still on progress? In my tests DartSass was up to 10 times slower, what is not acceptable for a "runtime-compiling" stylesheet.

**Comment by kgwood39** [comment]
Is it possible to include the DartSass project with the BundleTransformer?  I am attempting to use BootStrap 5.2 Scss files in my project but it won't compile with the existing BundleTransformer.SassAndScss adapter.  Would love to see progress in this direction?

**Comment by Taritsyn** [comment]
Hello, Kevin!

For now, use the [BundleTransformer.SassAndScss](https://www.nuget.org/packages/BundleTransformer.SassAndScss/#versions-body-tab) package from version [1.13.0 Preview 3](https://github.com/Taritsyn/BundleTransformer/releases/tag/v1.13.0-preview.3). To use a more recent version of Sass, simply update the [DartSassHost](https://www.nuget.org/packages/DartSassHost/) package.

Steps required to update the BundleTransformer.SassAndScss module to version 1.13.X:
 1. Update the BundleTransformer.SassAndScss package to latest preview version.
 1. Uninstall the LibSassHost and LibSassHost.Native.* packages if necessary.
 1. Remove the `precision` and `sourceComments` attributes from the `/configuration/bundleTransformer/sassAndScss` configuration element in the `Web.config` file.
 1. Install one of the following packages: [JavaScriptEngineSwitcher.Msie](https://www.nuget.org/packages/JavaScriptEngineSwitcher.Msie) (only in the Chakra “Edge” JsRT mode), [JavaScriptEngineSwitcher.V8](https://nuget.org/packages/JavaScriptEngineSwitcher.V8) or [JavaScriptEngineSwitcher.ChakraCore](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore/).
 1. [Register a JS engine](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines).
 1. Set a name of JS engine (for example, `MsieJsEngine`) to the `name` attribute of `/configuration/bundleTransformer/sassAndScss/jsEngine` configuration element in the `Web.config` file.

**Comment by kgwood39** [comment]
Wow!  Thank you for the fast response.  I very much appreciate all of your efforts in this area over the years.

With your assistance, I was able to get it to work with Framework 4.8 and the ChakraEngine.  There was no <sassAndScss> element so it had to be added:
    <sassAndScss>
      <jsEngine name="ChakraCoreJsEngine"/>
    </sassAndScss>

Both BundleTransformer.SassAndScss and DartSassHost are in the preview phase and have been for some time (12/11/2021!!).  I see your commits from today of the DartSassHost.  Fantastic.  

So many people could benefit from having a working DartSaasHost in the .Net space.  What more needs to be done to make this a release and is there anything I can do to help?

**Comment by Taritsyn** [comment]
>  What more needs to be done to make this a release and is there anything I can do to help?

If nothing unexpected happens, then I will make a stable release next week.

**Comment by Taritsyn** [comment]
Hello!

[First stable release](https://github.com/Taritsyn/DartSassHost/releases/tag/v1.0.0) of the Dart Sass Host was released yesterday.
