### ISSUE TITLE
Visual studio 2017 can't install JavaScriptEngineSwitcher.V8

### ISSUE THREAD

**Issue by clarghi** [Taritsyn/BundleTransformer#49]
Hi,
I have used this package in vs2019 without problems.
Now I must install in a big vs2017 project, but JavaScriptEngineSwitcher.V8 cannot be installed because has a dependency with ClearScript.Core v7.1.2 which must use nuget 5.3.0.
But NUGET 5.3.0, if I have understood correctly, is not installable in vs 2017 but only in vs2019:
https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.3
Is right? So, is this package no more compatible with vs 2017? Any workaround?
b.r.
Cristiano Larghi

**Comment by Taritsyn** [comment]
Hello, Cristiano!

First of all, I recommend that you write about this problem to authors of the [ClearScript](https://github.com/Microsoft/ClearScript) library.

There are only two workarounds so far: 
 1. Roll back a JavaScriptEngineSwitcher.V8 module to version 3.5.5.
 1. Replace a JavaScriptEngineSwitcher.V8 module by the [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/ChakraCore) module.

**Comment by Taritsyn** [comment]
Hello, Cristiano!

In new version of the ClearScript library has [solved this problem](https://github.com/microsoft/ClearScript/releases/tag/7.1.5). So try updating the JavaScriptEngineSwitcher.V8 module to [version 3.12.5](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.12.5).
