### ISSUE TITLE
Closure doesn't support ECMASCRIPT6/ECMASCRIPT6_STRICT on remote plugin

### ISSUE THREAD

**Issue by minimonsters** [Taritsyn/BundleTransformer#52]
The optional request parameters for the API support ecmascript6 tags, but the library seems to enforce its own type checking on this field and only allows up to ecmascript5 to work

I would suggest, for future-proofing, that you let google tell us that the language variable supplied is invalid (same with any other variables)

Thank you for providing this library!

https://developers.google.com/closure/compiler/docs/api-ref#opt

**Comment by Taritsyn** [comment]
Thanks for information!

**Comment by Taritsyn** [comment]
This problem has been fixed in [version 1.12.39](https://github.com/Taritsyn/BundleTransformer/releases/tag/v1.12.39).
