### ISSUE TITLE
Problem with updates to latest version of SassAndScss

### ISSUE THREAD

**Issue by trevski** [Taritsyn/BundleTransformer#56]
We are running locally on IIS on Windows 10.
We are upgrading our project to run on Bootstrap5 using SASS and moving away from .less.
Initially SASS was working but then I decided to clean up the nuget packages and upgrade to the latest version. 1.12.36 and LibSassHost 1.3.3

We are now getting a very unhelpful error message.

Exception has been thrown by the target of an invocation.

[HttpException (0x80004005): During the output text content of processed asset an unknown error has occurred.
See more details:
Exception has been thrown by the target of an invocation.]
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.ProcessRequest(HttpContextBase context) +1619
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +542
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +75
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +93

Can you provide any ideas as to how we might debug?

**Comment by Taritsyn** [comment]
Hello, Trevor!

Have you installed the [LibSassHost.Native.win-x86](https://www.nuget.org/packages/LibSassHost.Native.win-x86) and [LibSassHost.Native.win-x64](https://www.nuget.org/packages/LibSassHost.Native.win-x64) packages?

**Comment by trevski** [comment]
Only x64

**Comment by Taritsyn** [comment]
Is the process definitely not 32-bit?

**Comment by trevski** [comment]
I have installed x86 and still have the same issue. I am running Visual Studio Enterprise 2022 so I assumed we were debugging in x64.

**Comment by trevski** [comment]
<packages>
  <package id="AdvancedStringBuilder" version="0.1.0" targetFramework="net472" />
  <package id="Antlr" version="3.5.0.2" targetFramework="net48" />
  <package id="BundleTransformer.Core" version="1.10.0" targetFramework="net472" />
  <package id="BundleTransformer.SassAndScss" version="1.12.36" targetFramework="net472" />
  <package id="JavaScriptEngineSwitcher.Core" version="3.3.0" targetFramework="net472" />
  <package id="JavaScriptEngineSwitcher.V8" version="3.17.4" targetFramework="net472" />
  <package id="LibSassHost" version="1.3.3" targetFramework="net472" />
  <package id="LibSassHost.Native.win-x64" version="1.3.3" targetFramework="net472" />
  <package id="LibSassHost.Native.win-x86" version="1.3.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net472" />
  <package id="Microsoft.ClearScript.Core" version="7.2.4" targetFramework="net472" />
  <package id="Microsoft.ClearScript.V8" version="7.2.4" targetFramework="net472" />
  <package id="Microsoft.ClearScript.V8.Native.win-x64" version="7.2.4" targetFramework="net472" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="13.0.1" targetFramework="net472" />
  <package id="System.Buffers" version="4.0.0" targetFramework="net472" />
  <package id="WebGrease" version="1.6.0" targetFramework="net48" />
</packages>

**Comment by Taritsyn** [comment]
It is very similar to absence of some dependency or usage of incompatible versions of assemblies.

If I were you, I would uninstall all NuGet packages, and then install only the necessary ones. In the latest versions of Visual Studio, error often occur when updating packages in the legacy ASP.NET projects (see the [“Need BundleTransformer.NUglify new package release”](https://github.com/Taritsyn/BundleTransformer/issues/54) and [“Updating System.Buffers in .Net Framework project breaks dll-mapping to libsasshost version”](https://github.com/Taritsyn/LibSassHost/issues/51) issues).

**Comment by trevski** [comment]
I believe that is exactly what I have done, although I have other code that requires an update to Newtonsoft which is now on version 13.

Is there any way of telling which assembly is incompatible ?

**Comment by Taritsyn** [comment]
> Is there any way of telling which assembly is incompatible?

It's hard to say, but the LibSassHost doesn't use the Json.NET library.

It is also possible that an error at the interop level and occurs when reading files. Try translate a simple SCSS-file without imports instead of the Bootstrap.

**Comment by trevski** [comment]
One of the dependencies is WebGrease which does require Json.Net

I've done a clean install as you have suggested.

System.Buffers needed to be pushed to latest version 4.5.1
Microsoft.Web.Infrastructure needed to be pushed to 2.0.0

in order for the project to compile

I then found an error here 

<section name="sassAndScss" type="BundleTransformer.SassAndScss.Configuration.SassAndScssSettings, BundleTransformer.SassAndScss" />

with a clash on my machine level web.config which I suspect was the root of the issue.

It is now resolved thank you for your help.

**Comment by trevski** [comment]
Happy to close thank you for your help again.

**Comment by trevski** [comment]
Quick questions, which css minifier would you recommend ?

**Comment by Taritsyn** [comment]
[BundleTransformer.NUglify](https://www.nuget.org/packages/BundleTransformer.NUglify) it is a modern replacement for the BundleTransformer.MicrosoftAjax module.
