### ISSUE TITLE
Web Grease minifier when deployed to an Azure App Service results in Could not load file or assembly 'MFCMIFC80, Version=1.0.0.0

### ISSUE THREAD

**Issue by JohnMcAvinue** [Taritsyn/BundleTransformer#6]
Hi,

I switched from Azure Cloud Services to App Services and when I deployed I got a loader exception (2 actuall):

Could not load file or assembly 'MFCMIFC80, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I changed from Web Grease to KryzhanovskyCssMinifier and it works fine now.

**Comment by Taritsyn** [comment]
Hello, John!

First, it's a deployment error, and you need to fix it yourself (or write a letter to the App Services support team). I recommend you to read the following discussions: [“Is MFCMIFC80 a part of a redistributable package?”](https://social.msdn.microsoft.com/Forums/windows/en-US/b4dd1a7b-2b13-4a77-a7b2-7bd3d800b0bd/is-mfcmifc80-a-part-of-a-redistributable-package?forum=winformssetup) and [“Windows Azure Error - Could not load file or assembly MFCMIFC80”](https://stackoverflow.com/questions/30808359/windows-azure-error-could-not-load-file-or-assembly-mfcmifc80).

Secondly, this error is not directly related to the BundleTransformer.WG module. [WebGrease](http://webgrease.codeplex.com/) library refers to the `System.Windows.Forms` assembly, which depends on the `MFCMIFC80.dll`. You can [write about this problem to the WebGrease's developers](http://webgrease.codeplex.com/workitem/list/basic).
