### ISSUE TITLE
BundleTransformer.Less does not work with ASPNET MVC5 in Docker

### ISSUE THREAD

**Issue by richardzyx** [Taritsyn/BundleTransformer#7]
I had an issue working with bundle transformer in docker, a more detailed discussion can be found [here](https://github.com/Microsoft/aspnet-docker/issues/51)

I have tried turning enable optimizations on and off and still doesn't work. Any idea on how to keep poking into the code base, or what the likely cause might be? It most certainly has something to do with how System.Web.Optimization interacts with bundle transformer, but I am not familiar enough with the package setup to dig deeper.

Any advice or suggestion is deeply appreciated. Thanks!

**Comment by Taritsyn** [comment]
What version of Internet Explorer is installed on the server?

**Comment by richardzyx** [comment]
The docker image was built using on this as the base image https://hub.docker.com/r/microsoft/aspnet/ I'm not sure what version of IE they use in Server Core.

Actually, just based on a quick search, I see an IE is not installed: https://msdn.microsoft.com/en-us/library/dd184075.aspx

**Comment by richardzyx** [comment]
Does that mean bundle transformer wouldn't work without the IE in the base OS image? Based on this discussion https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214 it seems that hopes for an IE docker image will be unrealistic in near future.

**Comment by Taritsyn** [comment]
> Actually, just based on a quick search, I see an IE is not installed: https://msdn.microsoft.com/en-us/library/dd184075.aspx

In description of the [JavaScriptEngineSwitcher.Msie](https://www.nuget.org/packages/JavaScriptEngineSwitcher.Msie) package and [documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-MSIE) clearly says: “For correct working of the MSIE JavaScript Engine it is recommended to install Internet Explorer 9+ or Microsoft Edge on the machine.”.

Install a Internet Explorer 9+ or replace the JavaScriptEngineSwitcher.Msie module by the [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore) module.

**Comment by richardzyx** [comment]
Thanks for your response! I think installing IE in a docker image is pretty hopeless at this point, so I will try out the ChakraCore module and see if it works. Thank you for pointing that requirement out!

**Comment by richardzyx** [comment]
Switching to ChakraCore has been very successful, solved our issue and didn't break any existing unit tests or server infrastructure. It's probably worth adding this as a note for working with docker.

Thanks! I will close this issue now.
