### ISSUE TITLE
NUglifyJsMinifier appears to be incompatible with TypeScript enums that are transpiled to ES2015

### ISSUE THREAD

**Issue by RudeySH** [Taritsyn/BundleTransformer#79]
The `NUglifyJsMinifier` throws an error when it encounters a transpiled TypeScript enum.

Example TypeScript enum:
```ts
enum AchievementsDisplayMode {
    All = 0,
    Unrestricted = 1,
}
```

This enum gets transpiled into: (at least when targeting ES2015)
```js
"use strict";
var AchievementsDisplayMode;
(function (AchievementsDisplayMode) {
    AchievementsDisplayMode[AchievementsDisplayMode["All"] = 0] = "All";
    AchievementsDisplayMode[AchievementsDisplayMode["Unrestricted"] = 1] = "Unrestricted";
})(AchievementsDisplayMode || (AchievementsDisplayMode = {}));
```

When I run my application, I get the following exception:
```
BundleTransformer.NUglify.NUglifyParsingException: Message: Strict-mode does not allow assignment to undefined variables: AchievementsDisplayMode
Error code: JS1300
Severity: 0
Subcategory: run-time
File: /scripts/Generated/AchievementsDisplayMode.js
Start line: 6
Start column: 32
End line: 6
End column: 55
```

NUglify itself seems to work fine:
```cs
var result = Uglify.Js(@"""use strict"";
var AchievementsDisplayMode;
(function (AchievementsDisplayMode) {
    AchievementsDisplayMode[AchievementsDisplayMode[""All""] = 0] = ""All"";
    AchievementsDisplayMode[AchievementsDisplayMode[""Unrestricted""] = 1] = ""Unrestricted"";
})(AchievementsDisplayMode || (AchievementsDisplayMode = {}));");

Console.WriteLine(result.Errors.Count); // -> 0
```

How come NUglify is able to parse the JS without errors, while BundleTransformer throws an `NUglifyParsingException`?

As a workaround you can disable strict mode, but that is not an acceptable solution.

**Comment by RudeySH** [comment]
I did some more testing. Even with slightly more advanced usage of NUglify, it is able to parse the js just fine.

```cs
var parser = new JSParser
{
    Settings = new CodeSettings
    {
        StrictMode = true,
    },
};

var result = parser.Parse(@"""use strict"";
var AchievementsDisplayMode;
(function (AchievementsDisplayMode) {
AchievementsDisplayMode[AchievementsDisplayMode[""All""] = 0] = ""All"";
AchievementsDisplayMode[AchievementsDisplayMode[""Unrestricted""] = 1] = ""Unrestricted"";
})(AchievementsDisplayMode || (AchievementsDisplayMode = {}));");

parser.CompilerError += (x, y) =>
{
    // This event never fires.
};
```

**Comment by Taritsyn** [comment]
Hello, Rudey!

I can't reproduce this error using the default settings of the BundleTransformer.NUglify module. It is possible that you are using some other settings or old version of the BundleTransformer.NUglify module.

Try to reproduce this error in the form of demo project and send me a link to it.

**Comment by RudeySH** [comment]
While creating the demo project, I figured out what was wrong.

My bundle included a JS file that uses the enum before the enum JS file itself was included. Apparently this was never a problem while using the built-in ScriptBundle. I began using CustomScriptBundle and NullOrderer today, which is probably why this issue popped up. I solved the issue by including all enums before any other includes.
