### ISSUE TITLE
[Q] Is there any way to use this library outside of MVC project?

### ISSUE THREAD

**Issue by dehghani-mehdi** [Taritsyn/BundleTransformer#8]
Hi,

I want to use the `Autoprefixer` and `SASS` modules in `Console app`, is that possible?

Thanks.

**Comment by Taritsyn** [comment]
Hello, Mehdi!

Bundle Transformer is intended only for use in ASP.NET web applications and sites. If you only need a Sass compilation, then you can use the [LibSass Host for .NET](https://github.com/Taritsyn/LibSassHost) library directly.

**Comment by dehghani-mehdi** [comment]
Thanks for the answer. I tired that, also NSass, but none of them doesn't support `autoprefixing`. do you know any way to do `autoprefixing` using `C#` in `Console app`?

**Comment by Taritsyn** [comment]
> do you know any way to do `autoprefixing` using `C#` in `Console app`?

I do not know.

**Comment by dehghani-mehdi** [comment]
Thanks. is there any chance to use your library in console app, I mean have you any plan to add this feature?

**Comment by Taritsyn** [comment]
While there are no such plans.
