### ISSUE TITLE
disableClientCache/disableServerCache not working

### ISSUE THREAD

**Issue by p3tar** [Taritsyn/BundleTransformer#9]
I've tried setting both disableClientCache and disableServerCache to true under assetHandler configuration section and tested for both configuration modes (true/false). CSS and JS resources still get read from disk cache (Chrome).

**Comment by Taritsyn** [comment]
Hello, Petar!

Your web application is in release or debug mode?

**Comment by p3tar** [comment]
Hello, 

My web app was set to debug mode the whole time, I see now that when I set it to debug false that I get a content hash query string at the end of my bundle URL. So do I need to use disableClientCache or disableServerCache in debug=false mode at all, or those are only used for debug=true.

Thank you.

**Comment by Taritsyn** [comment]
> ... I set it to debug false that I get a content hash query string at the end of my bundle URL.

Unfortunately, this functionality is not supported in debug mode, because there is no technical possibility to implement this functionality.

> So do I need to use disableClientCache or disableServerCache in debug=false mode at all, ...

These settings apply only to the [debugging HTTP handlers](https://github.com/Taritsyn/BundleTransformer/wiki/Debugging-HTTP-handlers).

**Comment by p3tar** [comment]
Everything works fine with content hash added to the bundle URL when debug mode is set to false. As soon as something gets changed content hash is different and end user/client gets the latest version of CSS/JS file. 

Sadly sometimes someone forgets to set debug mode to false... and there is no content hash querystring when reading bundle files in debug mode true (uncombined).

**Comment by Taritsyn** [comment]
> Everything works fine with content hash added to the bundle URL when debug mode is set to false. As soon as something gets changed content hash is different and end user/client gets the latest version of CSS/JS file.

This functionality is provided by the [Microsoft ASP.NET Web Optimization Framework](http://aspnetoptimization.codeplex.com/).

> Sadly sometimes someone forgets to set debug mode to false... and there is no content hash querystring when reading bundle files in debug mode true (uncombined).

If you do not register the `CssAssetHandler` and `JsAssetHandler` handlers, then your files are sent directly via the web server.

**Comment by p3tar** [comment]
I understand, thank you for explanations. Great work.
